language: java

env:
  matrix:
    - PROFILE=ci
    - PROFILE=spring52-next
    - PROFILE=hibernate-next
jobs:
  allow_failures:
    - env: PROFILE=hibernate-next

cache:
  directories:
    - $HOME/.m2

install: true

script: "mvn clean dependency:list test -Pjava11,${PROFILE} -Dsort -B"
